### REST Data HTTP service
server.port=8090
server.servlet.context-path=/DSA-SQL-oracle/rest

### JDBC Data Source (Oracle)
jdbc.data.source.DB_URL=jdbc:oracle:thin:@localhost:1521/XEPDB1
jdbc.data.source.USER=FDBO
jdbc.data.source.PASS=fdbo_pass
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# logging
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n
logging.level.org.hibernate.SQL=debug

# SpringBoot Security
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
spring.security.user.name=developer
spring.security.user.password=iis
